#! /bin/bash

export LANGUAGE="hu_HU:hu"
export LANG="hu_HU.UTF-8"
export LC_COLLATE="hu_HU.UTF-8"
export LC_CTYPE="hu_HU.UTF-8"
export LC_MESSAGES="hu_HU.UTF-8"
export LC_MONETARY="hu_HU.UTF-8"
export LC_NUMERIC="hu_HU.UTF-8"
export LC_TIME="hu_HU.UTF-8"
export LC_ALL=
